### ISSUE TITLE
Missing goal in explainer

### ISSUE THREAD

**Issue by NSoiffer** [mathml-refresh/mathml-core#22]
Maybe controversial, maybe not, but I feel an important goal is left out of the explainer: _Maintain compatibility with non web-based usages of MathML_.

As mentioned later in the explainer, MathML has a vibrant eco-system outside of the web. A goal of core should be to maintain compatibility with that ecosystem. One consequence of this goal is that "this element is not needed because it duplicates CSS" is not a viable argument. Core may simply map that element to CSS attributes, but eliminating the element would cause problems for non-web usage of MathML.

**Comment by fred-wang** [comment]
I think we agree that maintaining compatibility with non web-based is a goal of the MathML CG but I'm not sure it is a goal of the MathML Core spec, or at least not as a standalone spec. I believe what @bkardell has written in the explainer is to explain how core defines a minimal CSS-compatible subset that we can extend with web extensible principle (including to support legacy MathML3 feature if necessary).

So I disagree with your "One consequence of this...", removing a legacy MathML feature is perfectly valid and even more if it causes duplication. This principle applies for MathML 4 Full which cares about backward compatibility with MathML3, but that's not the spec described by the explainer or that browser implementers care about.

**Comment by bkardell** [comment]
I think this is very hard to say without just generating confusion, tbh.  The implication is that, and I think that should probably remain an implication.  Maybe we can agenda+ this if you think it needs more discussion?

**Comment by fred-wang** [comment]
Closing as this is not a goal for the MathML Core spec but for the CG and as Brian said aspect is going to (actually has already) generated a lot of confusions from externals, which is what I'm trying to solve.
