### ISSUE TITLE
Decide the name of the spec and rename everywhere

### ISSUE THREAD

**Issue by fred-wang** [mathml-refresh/mathml-core#4]
The spec is referred by many names in various places:

* targets the Web: "MathML in HTML5", "web profile", "straw man mathml in html experiments"
* subset of the main spec: "mml-redux", "MathML Core"

W3C specs are supposed to target the Web so it seems a bit redundant to say that we have a "Web profile" for MathML and suggests MathML is actually not supposed to have the Web as its main target.

Also feedback from W3C and browser vendors, it seems their interest is really on having a subset that can be implemented in an interoperable way, relying as much as possible on other Web features. So my preference would be "MathML Core" to highlight its importance with respect to a bigger MathML spec.

**Comment by davidcarlisle** [comment]
I quite like "mathml web profile" (but it is a bit long for a name) but "mathml core" is also OK, and I agree that whatever it is we should use same everywhere.  Something the group should decide in its first telecon, then change the draft to match.

**Comment by davidcarlisle** [comment]
should be using mathml core now everywhere, closing.
